configs:
  - name: NTQBSWHF_BBIW
    match: 'NTQBSWHF_'      # substring or regex (we'll use it as regex)
    delimiter: ';'
    map:
      1: KC_ESTORETRX_ID
      2: KC_ORDER_ID
      3: KC_PARTNER_NO
      5: KC_PRODUCT_NO
      6: KC_ECHEQUE_NO
      8: LDD

  - name: NTQTOPFU_BBIU
    match: 'NTQTOPFU_'
    delimiter: ';'
    map:
      1: KC_ORDER_ID
      2: KC_PARTNER_NO
      4: KC_PRODUCT_NO
      20: LDD
